{% set name = "jupyterlab-link-share" %}
{% set version = "0.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab-link-share-{{ version }}.tar.gz
  sha256: fd62aadd9428cb0303e29e27a660f886bdbf28beaac212d73dac9d038eb8c09b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - jupyter-packaging >=0.7.9,<1
  run:
    - jupyterlab >=3.0.0,<4
    - python >=3.6

test:
  imports:
    - jupyterlab_link_share
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/jupyterlab-link-share/package.json"                                    # [unix]
    - test -f "${PREFIX}/etc/jupyter/jupyter_server_config.d/jupyterlab_link_share.json"                                    # [unix]
    - test -f "${PREFIX}/etc/jupyter/jupyter_notebook_config.d/jupyterlab_link_share.json"                                  # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-link-share\\package.json (exit 0) else (exit 1)          # [win]
    - if exist %PREFIX%\\etc\\jupyter\\jupyter_server_config.d\\jupyterlab_link_share.json (exit 0) else (exit 1)           # [win]
    - if exist %PREFIX%\\etc\\jupyter\\jupyter_notebook_config.d\\jupyterlab_link_share.json (exit 0) else (exit 1)           # [win]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-link-share
  summary: JupyterLab Extension to share the URL to a running Jupyter Server
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
    - fcollonval
